services:
  - type: web
    name: krisper
    runtime: node
    plan: free
    buildCommand: npm install --prefix krisper
    startCommand: node krisper/src/index.js
    envVars:
      - key: NODE_ENV
        value: development
      - key: VERIFY_TOKEN
        sync: false
      - key: node
        value: 3000
